# Environment Variables
export PATH=$HOME/bin:/usr/local/bin:/Applications/Racket\ v7.1/bin:$PATH
export ARCHFLAGS="-arch x86_64"
export LANG=en_US.UTF-8
export SSH_KEY_PATH="~/.ssh/rsa_id"
export GPG_TTY=$(tty)
export EDITOR='nvim'
export GEOMETRY_STATUS_COLOR="magenta"
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python3
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/Workspace
export FZF_DEFAULT_COMMAND='rg --files 2> /dev/null'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export KEYTIMEOUT=1

# Keybindings
bindkey -v
bindkey "^R" history-incremental-pattern-search-backward

# Aliases
alias comp++='clang++ -Wall -g -std=c++11 '
alias vim='nvim'
alias vi='nvim'
alias pdoc='pandoc --from=markdown --pdf-engine=xelatex --output=output.pdf '

if command -v pyenv 1>/dev/null 2>&1; then
    eval "$(pyenv init -)"
fi

# Sourcing
source $HOME/.config/zsh-plugin/geometry/geometry.zsh
source /usr/local/bin/virtualenvwrapper.sh
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
